version: "2"
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
volumes:
  dbdata6:
